### PR TITLE
Change sweep to use yml config

### LINKED ISSUE #112: Rework sweeps config to use yml

### PR DESCRIPTION
**Pull request by marco-bazzani**

### CODE REVIEW

**Comment by benjamin-cates** [comment]
Is the sweeps.yml added to the gitignore?

**Review by benjamin-cates — DISMISSED** [review]
Looks to good me

**Review by benjamin-cates — DISMISSED** [review]
File rename okay I guess

**Review by Sean1572 — CHANGES_REQUESTED** [review]
Add default sweep config. No automatic work needed just be nice to have a working example.

**Review by Sean1572 — APPROVED** [review]
Perfect

**Pull request merged**
