### PR TITLE
Clean up error message to let user know what to change

### PR DESCRIPTION
**Pull request by Sean1572**

### CODE REVIEW

**Comment by Sean1572** [comment]
Current error output:
```
InvalidGitRepositoryError found, likely reproduciblity issue
You are likely calling a python file outside of this repo, please make you python statement be in the repo
Traceback (most recent call last):
  File "C:\Users\seanh\Desktop\E4E\acoustic-species-classification\classification\config.py", line 89, in get_config     
    repo = git.Repo(search_parent_directories=True)
  File "C:\Users\seanh\.conda\envs\asid\lib\site-packages\git\repo\base.py", line 265, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: C:\Users\seanh\Desktop\E4E

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\acoustic-species-classification\classification\train.py", line 317, in <module>
    main()
  File ".\acoustic-species-classification\classification\train.py", line 272, in main
    CONFIG = get_config()
  File "C:\Users\seanh\Desktop\E4E\acoustic-species-classification\classification\config.py", line 96, in get_config     
    raise OSError("TO FIX: CALL PYTHON SCRIPT FROM REPO TO SAVE GIT HASH")
OSError: TO FIX: CALL PYTHON SCRIPT FROM REPO TO SAVE GIT HASH
```

**Comment by Sean1572** [comment]
new output if script is called from incorrect folder:
```
InvalidGitRepositoryError found, likely reproduciblity issue
You are likely calling a python file outside of this repo, please make you python statement be in the repo
TO FIX: CALL PYTHON SCRIPT FROM REPO TO SAVE GIT HASH
```

**Comment by benjamin-cates** [comment]
I checked and it does show up on wandb 👍

**Review by benjamin-cates — APPROVED** [review]
I am happy with it

**Pull request merged**
