### PR TITLE
HOTFIX: improve gpu memory usage

### PR DESCRIPTION
**Pull request by Sean1572**
image

Obsreved that during the inner validation loop, the gpu utilization worsened resulting in CUDA out of memory errors.  This was because tensors for training were still within scope during validation. This change should fix this error by freeing those tensors from memory prior to validation run

### CODE REVIEW

**Comment by benjamin-cates** [comment]
I still noticed the same memory usage spikes during validation on my machine, prolly should test it first

**Comment by benjamin-cates** [comment]
There might be an official way to free them without del

**Comment by Sean1572** [comment]
> There might be an official way to free them without del

https://discuss.pytorch.org/t/how-to-delete-a-tensor-in-gpu-to-free-up-memory/48879/9

We can do empty cache but this seems to be enough

**Review by marco-bazzani — DISMISSED** [review]

**Review by benjamin-cates — APPROVED** [review]
I approve

**Pull request merged**
