### PR TITLE
Highpass Filter

### PR DESCRIPTION
**Pull request by marco-bazzani**

### CODE REVIEW

**Comment by benjamin-cates** [comment]
Should add this to testing

**Comment by benjamin-cates** [comment]
Oh we need to change N_AUGS on line 75 of aug_viewer.py..... It might be better to just have that be dynamic based on what get_augs returns

**Review by sprestrelski — CHANGES_REQUESTED** [review]
N_AUGS 😠

**Review by benjamin-cates — CHANGES_REQUESTED** [review]
Umm test this plzzzz

**Comment by benjamin-cates** [comment]
> N_AUGS 😠

@sprestrelski 

N_AUGS fixed 🥰
it is gone

**Review by benjamin-cates — DISMISSED** [review]
This works but I do not approve of the config stuff in aug_viewer but that's kinda outside the scope of this 😭

**Review by benjamin-cates — DISMISSED** [review]
Epic highpass filter moment

**Review by sprestrelski — APPROVED** [review]

**Pull request merged**
