### PR TITLE
Fast training

### PR DESCRIPTION
**Pull request by benjamin-cates**
Did a couple things to hopefully improve training speed. Config changes will have to be made and we will probably have to rename some columns on the csv

### CODE REVIEW

**Review by sprestrelski — CHANGES_REQUESTED** [review]
This created 500GB of cache files for the Peru Xeno-canto dataset and kastner ran out of storage.

**Comment by benjamin-cates** [comment]
> uhhh this made kastner run out of storage....

So maybe I should see if we can store it at half precision or something? I'll look into how that changes spectrogram quality

**Comment by benjamin-cates** [comment]
Caching is now optional if there's a storage constraint. Might look into smaller datatypes or storing it in a different format later

**Review by Sean1572 — APPROVED** [review]

**Review by Sean1572 — CHANGES_REQUESTED** [review]
Lets remove this cache code if it isn't going to help

**Comment by sprestrelski** [comment]
I agree. Although it works for small datasets, the whole point of the model refactor was to reduce storage requirements. IMO it's fine if the training takes a bit longer as a tradeoff.

**Pull request merged**
