### PR TITLE
Update .gitignore to use gitignore.io

### PR DESCRIPTION
**Pull request by sprestrelski**

### CODE REVIEW

**Comment by Sean1572** [comment]
hear me out, we change the code review links to this repo so when Friday comes, they are linked here and are immensely confused

**Comment by benjamin-cates** [comment]
That sounds like a good idea sean

**Comment by benjamin-cates** [comment]
Might want to add data_local since that's our aws folder name, but looks good

**Review by benjamin-cates — DISMISSED** [review]

**Review by Sean1572 — APPROVED** [review]
Checked on my machine

**Review by benjamin-cates — APPROVED** [review]

**Pull request merged**
