### PR TITLE
Remove progress bar from validation

### LINKED ISSUE #113: Fix wandb sweep log progress bars

### PR DESCRIPTION
**Pull request by marco-bazzani**
- Replaced with 25%/50%/75% progress markers
- Fixes #113

### CODE REVIEW

**Comment by marco-bazzani** [comment]
Still need to test if certain behaviors consistent with main

**Comment by marco-bazzani** [comment]
Note: after merging main code no longer runs, probably because of Sean's broken hotfix. Branch still needs to be tested before merging

**Comment by benjamin-cates** [comment]
I'm getting a `name "time" is not defined` error

**Review by benjamin-cates — APPROVED** [review]
Looks good, I checked that it works on wandb

**Review by Sean1572 — CHANGES_REQUESTED** [review]
Removing progress bar doesn't fix issue as issue is primarly caused by closing terminal window.

Keeping it open for now since maybe we should still remove it up we may want a deeper discussion for it.

**Comment by Sean1572** [comment]
@mbazzani @benjamin-cates Can we close this requestion w/out merge

**Comment by benjamin-cates** [comment]
Yeah go ahead lmaoooo

**Comment by marco-bazzani** [comment]
Yup

**Pull request closed without merging**
