### PR TITLE
Temp Main to test Changes

### PR DESCRIPTION
**Pull request by Sean1572**

### CODE REVIEW

**Comment by benjamin-cates** [comment]
It appears that the "partial validation" thing is not stopping at the right time 😭 . I'll do some debugging

**Comment by benjamin-cates** [comment]
Currently works, tested on AWS 👍

**Review by benjamin-cates — APPROVED** [review]
works on aws

**Review by sprestrelski — APPROVED** [review]
i'm being peer pressured :/

**Pull request merged**
